version: "3"

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:8000"
    command: npm run start
    logging:
      options:
        max-size: 50m

  # mongodb:
  #   image: mongo:4.2.1-bionic
  #   ports:
  #     - 27780:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: root
  #   volumes:
  #     - dbdata:/data/db

# volumes:
#   dbdata:
